- id: '1588947610767'
  alias: IFTTT webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: moo
  condition: []
  action:
  - data_template:
      message: '{{trigger.json.message}}'
    service: system_log.write
