automation:
  - id: 'raspbian_latest'
    alias: Raspbian Updated
    description: ''
    trigger:
      - entity_id: sensor.lastest_raspbian_release
        platform: state
    condition: 
      - condition: template
        value_template: "{{ not is_state ('sensor.lastest_raspbian_release', 'Unavailable') }}"
      
    action:
    - data_template:
        message: >
          Raspbian has been updated. See details [here](http://downloads.raspberrypi.org/raspbian/release_notes.txt).
          State changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}
        title: Raspbian Updated
      service: persistent_notification.create